export const homeObjOne = {
    id: 'sustainable',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Sustainable',
    headline: 'We are committed to sustainability',
    description:
        'We are agents of change. We challenge and push boundaries in a way that is fit for the world we live in today and the future: beautiful and sustainable. No compromises.',
    buttonLabel: 'Info',
    imgStart: true,
    img: require('../../images/svg/environment.svg').default,
    alt: 'digital tree',
    primary: false,
    darkText: true,
};
export const homeObjTwo = {
    id: 'wellness',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Wellness',
    headline: '',
    description:
        'We are agents of change. We challenge and push boundaries in a way that is fit for the world we live in today and the future: beautiful and sustainable. No compromises.',
    buttonLabel: 'Info',
    imgStart: false,
    img: require('../../images/svg/energy.svg').default,
    alt: 'digital tree',
    primary: false,
    dark: false,
    darkText: true,
};
export const homeObjThree = {
    id: 'quality',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topline: 'Quality',
    headline: 'Natural Ingredients',
    description:
        'Superior quality and great tasting, healthy, natural and functional beverages. Our beverages will be positioned as an upscale brand and will often be marketed at a premium for competitive mainstream products.',
    buttonLabel: 'Info',
    imgStart: false,
    img: require('../../images/svg/refresh.svg').default,
    alt: 'digital tree',
    primary: false,
    dark: false,
    darkText: true,
};
